[project]
name = "rice"
version = "0.1.0"
description = "You like rice and beans?"
dependencies = ["requests", "aiohttp", "pillow"]

[project.scripts]
reddit = "reddit.__main__:main"
rice = "reddit.wal:main"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["python"]
