[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dwagoon"
version = "0.1.0"
description = "Download wallpapers and goon"
dependencies = ["requests", "aiohttp", "pillow", "pywal16", "colorz"]

[project.scripts]
reddit = "dwagoon.scripts.reddit:main"
wal = "pywal.__main__:main"
rice = "dwagoon.scripts.rice:main"
rice2 = "dwagoon.scripts.rice:main"
savewall = "dwagoon.scripts.savewall:main"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["dwagoon"]
include-package-data = true
